openapi: 3.1.0
info:
  title: Open Payments
  version: '1.0'
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  description: |-
    The Open Payments API is a simple REST API with 4 resource types: **account**, **quote**, **incoming payment** and **outgoing payment**.  

    The *service endpoint* for the API is always the URL of the account resource and all other resources are sub-resources of the account.  

    All resource and collection resource representations use JSON and the media-type `application/json`.  

    The `account` resource has three collections of sub-resources and a single **account holder** sub-resource:   
    1. `/incoming-payments` contains the **incoming payment** sub-resources  
    2. `/outgoing-payments` contains the **outgoing payment** sub-resources  
    3. `/quotes` contains the **quote** sub-resources  

    Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
  summary: An API for open access to financial accounts to send and receive payments.
  contact:
    email: tech@interledger.org
servers:
  - url: 'https://openpayments.guide'
tags:
  - name: account
    description: account operations
  - name: incoming-payment
    description: incoming payment operations
  - name: outgoing-payment
    description: outgoing payment operations
  - name: quote
    description: quote operations
paths:
  '/{id}':
    get:
      summary: Get a Payment Pointer
      tags:
        - account
      responses:
        '200':
          description: Account Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
              examples:
                Get account for $openpayments.guide/alice:
                  value:
                    id: 'https://openpayments.guide/alice'
                    publicName: Alice
                    assetCode: USD
                    assetScale: 2
                    authServer: 'https://openpayments.guide/auth'
        '404':
          description: Account Not Found
      operationId: get-public-account
      description: |-
        Retrieve the public information of the account represented by the Payment Pointer.

        This end-point should be open to anonymous requests as it allows clients to verify a Payment Pointer URL and get the basic information required to construct new transactions and discover the grant request URL.

        The content should be slow changing and cacheable for long periods. Servers SHOULD use cache control headers.
      security: []
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Account identifier
  '/{accountId}/incoming-payments':
    post:
      summary: Create an Incoming Payment
      tags:
        - incoming-payment
      operationId: create-incoming-payment
      responses:
        '201':
          description: Incoming Payment Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
              examples:
                New Incoming Payment for $25:
                  value:
                    id: 'http://openpayments.guide/alice/incoming-payments/08394f02-7b7b-45e2-b645-51d04e7c330c'
                    accountId: 'http://openpayments.guide/alice/'
                    state: pending
                    incomingAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      value: '0'
                      assetCode: USD
                      assetScale: 2
                    expiresAt: '2022-02-03T23:20:50.52Z'
                    externalRef: INV2022-02-0137
                    ilpAddress: g.ilp.iwuyge987y.98y08y
                    sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
                    createdAt: '2022-03-12T23:20:50.52Z'
                    updatedAt: '2022-04-01T10:24:36.11Z'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                incomingAmount:
                  $ref: '#/components/schemas/amount'
                expiresAt:
                  type: string
                  description: The date and time when payments into the incoming payment must no longer be accepted.
                  format: date-time
                  writeOnly: true
                description:
                  type: string
                  description: Human readable description of the incoming payment that will be visible to the account holder.
                externalRef:
                  type: string
                  description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
              additionalProperties: false
            examples:
              Create incoming payment for $25 to pay invoice INV2022-02-0137:
                value:
                  incomingAmount:
                    value: '2500'
                    assetCode: USD
                    assetScale: 2
                  externalRef: INV2022-02-0137
        description: |-
          A subset of the incoming payments schema is accepted as input to create a new incoming payment.

          The `incomingAmount` must use the same `assetCode` and `assetScale` as the account.
      description: |-
        A client MUST create an **incoming payment** resource before it is possible to send any payments to the account. 

        All of the input parameters are _optional_.
    get:
      summary: List Incoming Payments
      operationId: list-incoming-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list-incoming-payments'
              examples:
                forward pagination:
                  value:
                    pagination:
                      startCursor: 241de237-f989-42be-926d-c0c1fca57708
                      endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                      hasNextPage: true
                      first: 10
                    result:
                      - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        incomingAmount:
                          value: '250'
                          assetCode: USD
                          assetScale: 2
                        receivedAmount:
                          value: '250'
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        createdAt: '2022-03-12T23:20:50.52Z'
                        updatedAt: '2022-04-01T10:24:36.11Z'
                        description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
                        externalRef: Coffee w/ Mo on 10 March 22
                      - id: 'https://openpayments.guide/alice/incoming-payments/32abc219-3dc3-44ec-a225-790cacfca8fa'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        receivedAmount:
                          value: '100'
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        createdAt: '2022-03-12T23:20:50.52Z'
                        updatedAt: '2022-04-01T10:24:36.11Z'
                        description: 'I love your website, Alice! Thanks for the great content'
                backward pagination:
                  value:
                    pagination:
                      startCursor: 241de237-f989-42be-926d-c0c1fca57708
                      endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                      hasPreviousPage: true
                      last: 10
                    result:
                      - id: 'https://openpayments.guide/alice/incoming-payments/32abc219-3dc3-44ec-a225-790cacfca8fa'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        receivedAmount:
                          value: '100'
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        createdAt: '2022-03-12T23:20:50.52Z'
                        updatedAt: '2022-04-01T10:24:36.11Z'
                        description: 'I love your website, Alice! Thanks for the great content'
                      - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        incomingAmount:
                          value: '250'
                          assetCode: USD
                          assetScale: 2
                        receivedAmount:
                          value: '250'
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        createdAt: '2022-03-12T23:20:50.52Z'
                        updatedAt: '2022-04-01T10:24:36.11Z'
                        description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
                        externalRef: Coffee w/ Mo on 10 March 22
          headers: {}
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      description: List all incoming payments on the account
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          in: query
          name: first
          description: 'The number of items to return, forward pagination'
        - schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          in: query
          name: last
          description: 'The number of items to return, backward pagination'
        - schema:
            type: string
          in: query
          name: cursor
          description: The cursor key to list from
      tags:
        - incoming-payment
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
  '/{accountId}/outgoing-payments':
    post:
      summary: Create an Outgoing Payment
      tags:
        - outgoing-payment
      operationId: create-outgoing-payment
      responses:
        '201':
          description: Outgoing Payment Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outgoing-payment'
              examples:
                New Fixed Send Outgoing Payment for $25:
                  value:
                    id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                    accountId: 'https://openpayments.guide/alice/'
                    failed: false
                    receivingPayment: 'https://openpayments.guide/bob/incoming-payments/48884225-b393-4872-90de-1b737e2491c2'
                    sendAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    sentAmount:
                      value: '0'
                      assetCode: USD
                      assetScale: 2
                    description: Thank you for the shoes.
                    createdAt: '2022-03-12T23:20:50.52Z'
                    updatedAt: '2022-04-01T10:24:36.11Z'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      requestBody:
        content:
          application/json:
            examples:
              Create an outgoing payment based on a quote:
                value:
                  quoteId: 'https://openpayments.guide/alice/quotes/ab03296b-0c8b-4776-b94e-7ee27d868d4d'
                  externalRef: INV2022-02-0137
            schema:
              type: object
              properties:
                quoteId:
                  type: string
                  format: uri
                  description: The URL of the quote defining this payment's amounts.
                  readOnly: true
                description:
                  type: string
                  description: Human readable description of the outgoing payment that will be visible to the account holder and shared with the receiver.
                externalRef:
                  type: string
                  description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
              additionalProperties: false
        description: |-
          A subset of the outgoing payments schema is accepted as input to create a new outgoing payment.

          The `sendAmount` must use the same `assetCode` and `assetScale` as the account.
      description: An **outgoing payment** is a sub-resource of an account. It represents a payment from the account.
    description: Create a new outgoing payment at the account.
    get:
      summary: List Outgoing Payments
      operationId: list-outgoing-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/list-outgoing-payments'
              examples:
                forward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasNextPage: true
                        first: 10
                      result:
                        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          failed: false
                          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
                          receiveAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sentAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          updatedAt: '2022-04-01T10:24:36.11Z'
                          description: APlusVideo subscription
                          externalRef: 'customer: 847458475'
                        - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          failed: false
                          receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          receiveAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          sentAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          updatedAt: '2022-04-01T10:24:36.11Z'
                          description: Thank you for your purchase at ShoeShop!
                          externalRef: INV2022-8943756
                backward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasPreviousPage: true
                        last: 10
                      result:
                        - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          failed: false
                          receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          receiveAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          sentAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          updatedAt: '2022-04-01T10:24:36.11Z'
                          description: Thank you for your purchase at ShoeShop!
                          externalRef: INV2022-8943756
                        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          failed: false
                          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
                          receiveAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sentAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          updatedAt: '2022-04-01T10:24:36.11Z'
                          description: APlusVideo subscription
                          externalRef: 'customer: 847458475'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      description: List all outgoing payments on the account
      parameters:
        - schema:
            type: integer
          in: query
          name: first
          description: 'The number of items to return, forward pagination'
        - schema:
            type: integer
          in: query
          name: last
          description: 'The number of items to return, backward pagination'
        - schema:
            type: string
          in: query
          name: cursor
          description: The cursor key to list from
      tags:
        - outgoing-payment
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
  '/{accountId}/quotes':
    post:
      summary: Create a Quote
      tags:
        - quote
      operationId: create-quote
      responses:
        '201':
          description: Quote Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quote'
              examples:
                New Fixed Send Quote for $25:
                  value:
                    id: 'https://openpayments.guide/alice/quotes/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                    accountId: 'https://openpayments.guide/alice/'
                    receivingAccount: 'https://openpayments.guide/bob/'
                    sendAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      value: '2198'
                      assetCode: EUR
                      assetScale: 2
                    createdAt: '2022-03-12T23:20:50.52Z'
                    expiresAt: '2022-04-12T23:20:50.52Z'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      requestBody:
        content:
          application/json:
            examples:
              Create fixed-send-amount quote for $25:
                value:
                  receivingAccount: 'https://openpayments.guide/alice'
                  sendAmount:
                    value: '2500'
                    assetCode: USD
                    assetScale: 2
              Create fixed-receive-amount quote for $25:
                value:
                  receivingPayment: 'https://openpayments.guide/alice/incoming-payments/37a0d0ee-26dc-4c66-89e0-01fbf93156f7'
                  receiveAmount:
                    value: '2500'
                    assetCode: USD
                    assetScale: 2
            schema:
              type: object
              properties:
                receivingAccount:
                  type: string
                  format: uri
                  description: The URL of the account that is being paid.
                receivingPayment:
                  type: string
                  format: uri
                  description: The URL of the incoming payment that is being paid.
                receiveAmount:
                  $ref: '#/components/schemas/amount'
                sendAmount:
                  $ref: '#/components/schemas/amount'
              additionalProperties: false
        description: |-
          A subset of the quotes schema is accepted as input to create a new quote.

          The quote must be created with (`receivingPayment` xor `receivingAccount`) and (`sendAmount` xor `receiveAmount`) or `receivingPayment` and no specified amount (assuming the Incoming Payment has an `incomingAmount`).
      description: A **quote** is a sub-resource of an account. It represents a quote for a payment from the account.
    description: Create a new quote at the account.
    get:
      summary: List Quotes
      operationId: list-quotes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/list-quotes'
              examples:
                forward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasNextPage: true
                        first: 10
                      result:
                        - id: 'https://openpayments.guide/alice/quotes/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
                          receiveAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          expiresAt: '2022-04-12T23:20:50.52Z'
                        - id: 'https://openpayments.guide/alice/quotes/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          receivingPayment: 'https://openpayments.guide/shoeshop/incoming-payments/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          receiveAmount:
                            value: '2198'
                            assetCode: EUR
                            assetScale: 2
                          createdAt: '2022-04-01T10:24:36.11Z'
                          expiresAt: '2022-05-01T10:24:36.11Z'
                backward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasPreviousPage: true
                        last: 10
                      result:
                        - id: 'https://openpayments.guide/alice/quotes/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          receivingPayment: 'https://openpayments.guide/shoeshop/incoming-payments/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          receiveAmount:
                            value: '7026'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-04-01T10:24:36.11Z'
                          expiresAt: '2022-05-01T10:24:36.11Z'
                        - id: 'https://openpayments.guide/alice/quotes/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
                          receiveAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            value: '2500'
                            assetCode: USD
                            assetScale: 2
                          createdAt: '2022-03-12T23:20:50.52Z'
                          expiresAt: '2022-04-12T23:20:50.52Z'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      description: List all quotes on the account
      parameters:
        - schema:
            type: integer
          in: query
          name: first
          description: 'The number of items to return, forward pagination'
        - schema:
            type: integer
          in: query
          name: last
          description: 'The number of items to return, backward pagination'
        - schema:
            type: string
          in: query
          name: cursor
          description: The cursor key to list from
      tags:
        - quote
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
  '/{accountId}/incoming-payments/{id}':
    get:
      summary: Get an Incoming Payment
      tags:
        - incoming-payment
      operationId: get-incoming-payment
      responses:
        '200':
          description: Incoming Payment Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
              examples:
                Incoming Payment for $25 with $12.34 received so far:
                  value:
                    id: 'https://openpayments.guide/alice/incoming-payments/2f1b0150-db73-49e8-8713-628baa4a17ff'
                    accountId: 'https://openpayments.guide/alice/'
                    state: processing
                    incomingAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      value: '1234'
                      assetCode: USD
                      assetScale: 2
                    expiresAt: '2022-04-12T23:20:50.52Z'
                    createdAt: '2022-03-12T23:20:50.52Z'
                    updatedAt: '2022-04-01T10:24:36.11Z'
                    description: Thanks for the flowers!
                    externalRef: INV-12876
                    ilpAddress: g.ilp.iwuyge987y.98y08y
                    sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Incoming Payment Not Found
      description: A client can fetch the latest state of an incoming payment to determine the amount received into the account.
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Incoming Payment identifier
    put:
      summary: Update an Incoming Payment
      operationId: update-incoming-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Incoming Payment Not Found
      description: |-
        A client with the appropriate permissions MAY update the state of an **incoming payment** to `completed` if it is in a state of `pending` or `processing`.

        This indicates to the receiving account provider that it can begin any post processing of the payment such as generating account statements or notifying the account holder of the completed payment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  enum:
                    - completed
              required:
                - state
              additionalProperties: false
            examples:
              Complete Incoming Payment:
                value:
                  state: completed
        description: Update the state of the incoming payment to `completed`.
      tags:
        - incoming-payment
  '/{accountId}/outgoing-payments/{id}':
    get:
      summary: Get an Outgoing Payment
      tags:
        - outgoing-payment
      operationId: get-outgoing-payment
      responses:
        '200':
          description: Outgoing Payment Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outgoing-payment'
              examples:
                Outgoing Payment with a fixed send amount of $25:
                  value:
                    id: 'https://openpayments.guide/bob/outgoing-payments/3859b39e-4666-4ce5-8745-72f1864c5371'
                    accountId: 'https://openpayments.guide/bob/'
                    failed: false
                    receivingPayment: 'http://openpayments.guide/alice/incoming-payments/2f1b0150-db73-49e8-8713-628baa4a17ff'
                    sendAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      value: '2198'
                      assetCode: EUR
                      assetScale: 2
                    sentAmount:
                      value: '1205'
                      assetCode: USD
                      assetScale: 2
                    createdAt: '2022-03-12T23:20:50.52Z'
                    updatedAt: '2022-04-01T10:24:36.11Z'
                    description: Thanks for the flowers!
                    externalRef: INV-12876
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Outgoing Payment Not Found
      description: A client can fetch the latest state of an outgoing payment.
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Outgoing Payment identifier
  '/{accountId}/quotes/{id}':
    get:
      summary: Get a Quote
      tags:
        - quote
      operationId: get-quote
      responses:
        '200':
          description: Quote Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quote'
              examples:
                Quote with a fixed send amount of $25:
                  value:
                    id: 'https://openpayments.guide/bob/quotes/3859b39e-4666-4ce5-8745-72f1864c5371'
                    accountId: 'https://openpayments.guide/bob/'
                    receivingPayment: 'http://openpayments.guide/alice/incoming-payments/2f1b0150-db73-49e8-8713-628baa4a17ff'
                    sendAmount:
                      value: '2500'
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      value: '2198'
                      assetCode: EUR
                      assetScale: 2
                    createdAt: '2022-03-12T23:20:50.52Z'
                    expiresAt: '2022-04-12T23:20:50.52Z'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Quote Not Found
      description: A client can fetch the latest state of a quote.
    parameters:
      - schema:
          type: string
          format: uuid
        name: accountId
        in: path
        required: true
        description: Account identifier
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Quote identifier
components:
  schemas:
    account:
      title: Account
      type: object
      description: An **account** resource is the root of the API and contains the public details of the financial account represented by the Payment Pointer that is also the service endpoint URL.
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          readOnly: true
        publicName:
          type: string
          description: A public name for the account. This should be set by the account holder with their provider to provide a hint to counterparties as to the identity of the account holder.
          readOnly: true
        assetCode:
          type: string
          description: The asset code of the account. This SHOULD be an ISO4217 currency code.
          readOnly: true
        assetScale:
          type: integer
          minimum: 0
          maximum: 255
          description: The scale of the account.
          readOnly: true
        authServer:
          type: string
          format: uri
          description: The URL of the authorization server endpoint for getting grants and access tokens for this account.
          readOnly: true
      additionalProperties: false
      examples:
        - id: 'https://openpayments.guide/alice'
          publicName: Alice
          assetCode: USD
          assetScale: 2
          authServer: 'https://openpayments.guide/auth'
    incoming-payment:
      title: Incoming Payment
      description: 'An **incoming payment** resource represents a payment that will be, is currently being, or has been received by the account.'
      type: object
      examples:
        - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
          accountId: 'https://openpayments.guide/alice/'
          state: completed
          incomingAmount:
            value: '250'
            assetCode: USD
            assetScale: 2
          receivedAmount:
            value: '250'
            assetCode: USD
            assetScale: 2
          expiresAt: '2022-04-12T23:20:50.52Z'
          createdAt: '2022-03-12T23:20:50.52Z'
          updatedAt: '2022-04-01T10:24:36.11Z'
          description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
          externalRef: Coffee w/ Mo on 10 March 22
          ilpApddress: g.ilp.iwuyge987y.98y08y
          sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account this payment is being made into.
          readOnly: true
        state:
          type: string
          description: The state of the payment as described above.
          enum:
            - pending
            - processing
            - completed
            - expired
          default: pending
        incomingAmount:
          $ref: '#/components/schemas/amount'
        receivedAmount:
          $ref: '#/components/schemas/amount'
        expiresAt:
          type: string
          description: The date and time when payments into the incoming payment will no longer be accepted.
          format: date-time
        description:
          type: string
          description: Human readable description of the incoming payment that will be visible to the account holder.
        externalRef:
          type: string
          description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
        ilpAddress:
          type: string
          description: The ILP address to use when establishing a STREAM connection.
          readOnly: true
        sharedSecret:
          type: string
          description: The shared secret to use when establishing a STREAM connection.
          readOnly: true
        createdAt:
          type: string
          format: date-time
          description: The date and time when the incoming payment was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time when the incoming payment was updated.
      required:
        - id
        - accountId
        - state
        - receivedAmount
        - createdAt
        - updatedAt
      additionalProperties: false
    outgoing-payment:
      title: Outgoing Payment
      description: 'An **outgoing payment** resource represents a payment that will be, is currently being, or has previously been, sent from the account.'
      type: object
      examples:
        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
          accountId: 'https://openpayments.guide/alice/'
          failed: false
          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
          receiveAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          sendAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          sentAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          createdAt: '2022-03-12T23:20:50.52Z'
          updatedAt: '2022-04-01T10:24:36.11Z'
          description: APlusVideo subscription
          externalRef: 'customer: 847458475'
        - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
          accountId: 'https://openpayments.guide/alice/'
          failed: false
          receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
          sendAmount:
            value: '7026'
            assetCode: USD
            assetScale: 2
          sentAmount:
            value: '7026'
            assetCode: USD
            assetScale: 2
          createdAt: '2022-03-12T23:20:50.52Z'
          updatedAt: '2022-04-01T10:24:36.11Z'
          description: Thank you for your purchase at ShoeShop!
          externalRef: INV2022-8943756
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the outgoing payment.
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account from which this payment is sent.
          readOnly: true
        quoteId:
          type: string
          format: uri
          description: The URL of the quote defining this payment's amounts.
          readOnly: true
        failed:
          type: boolean
          description: Describes whether the payment failed to send its full amount.
          default: false
        receivingPayment:
          type: string
          format: uri
          description: The URL of the incoming payment that is being paid.
        receiveAmount:
          $ref: '#/components/schemas/amount'
        sendAmount:
          $ref: '#/components/schemas/amount'
        sentAmount:
          $ref: '#/components/schemas/amount'
        description:
          type: string
          description: Human readable description of the outgoing payment that will be visible to the account holder and shared with the receiver.
        externalRef:
          type: string
          description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
        createdAt:
          type: string
          format: date-time
          description: The date and time when the outgoing payment was created.
        updatedAt:
          type: string
          format: date-time
          description: The date and time when the outgoing payment was updated.
      required:
        - id
        - accountId
        - receivingPayment
        - sendAmount
        - receiveAmount
        - sentAmount
        - createdAt
        - updatedAt
      additionalProperties: false
    quote:
      title: Quote
      description: A **quote** resource represents the quoted amount details with which an Outgoing Payment may be created.
      type: object
      examples:
        - id: 'https://openpayments.guide/alice/quotes/ab03296b-0c8b-4776-b94e-7ee27d868d4d'
          accountId: 'https://openpayments.guide/alice/'
          receivingPayment: 'https://openpayments.guide/shoeshop/incoming-payments/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
          receiveAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          sendAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          createdAt: '2022-03-12T23:20:50.52Z'
          expiresAt: '2022-04-12T23:20:50.52Z'
        - id: 'https://openpayments.guide/alice/quotes/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
          accountId: 'https://openpayments.guide/alice/'
          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
          sendAmount:
            value: '2500'
            assetCode: USD
            assetScale: 2
          receiveAmount:
            value: '2198'
            assetCode: EUR
            assetScale: 2
          createdAt: '2022-03-12T23:20:50.52Z'
          expiresAt: '2022-04-12T23:20:50.52Z'
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the quote.
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account from which this quote's payment would be sent.
          readOnly: true
        receivingPayment:
          type: string
          format: uri
          description: The URL of the incoming payment that would be paid.
        receiveAmount:
          $ref: '#/components/schemas/amount'
        sendAmount:
          $ref: '#/components/schemas/amount'
        expiresAt:
          type: string
          description: The date and time when the calculated `sendAmount` is no longer valid.
          readOnly: true
        createdAt:
          type: string
          format: date-time
          description: The date and time when the quote was created.
      additionalProperties: false
    amount:
      title: Amount
      type: object
      description: |-
        All amounts in open payments are represented as a value and an asset code and scale.

        The `value` is an unsigned 64-bit integer amount, represented as a string.

        The `assetCode` is a code that indicates the underlying asset. In most cases this SHOULD be a 3-character ISO 4217 currency code.

        The `assetScale` indicates how the `value` has been scaled relative to the natural scale of the asset. For example, an `value` of `"1234"` with an `assetScale` of `2` represents an amount of 12.34.
      examples:
        - value: '2500'
          assetCode: USD
          assetScale: 2
        - value: '500'
          assetCode: EUR
          assetScale: 2
        - value: '123456789'
          assetCode: BTC
          assetScale: 8
      properties:
        value:
          type: string
          format: uint64
          description: The amount that must be paid into the receiverâ€™s account.
        assetCode:
          type: string
          description: The asset code of the amount. This SHOULD be an ISO4217 currency code.
        assetScale:
          type: integer
          minimum: 0
          maximum: 255
          description: The scale of the amount.
      required:
        - value
        - assetCode
        - assetScale
      additionalProperties: false
    pagination:
      description: ''
      type: object
      examples:
        - startCursor: 241de237-f989-42be-926d-c0c1fca57708
          endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
          hasNextPage: true
          hasPreviousPage: true
          first: 10
          last: 10
      properties:
        startCursor:
          type: string
          minLength: 1
          description: Cursor corresponding to the first element in the result array.
        endCursor:
          type: string
          minLength: 1
          description: Cursor corresponding to the last element in the result array.
        hasNextPage:
          type: boolean
          description: Describes whether the data set has further entries.
        hasPreviousPage:
          type: boolean
          description: Describes whether the data set has previous entries.
        first:
          type: number
          description: Number of entries requested using forward pagination.
        last:
          type: number
          description: Number of entries requested using backward pagination.
      additionalProperties: false
    list-incoming-payments:
      title: list-incoming-payments
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        result:
          type: array
          items:
            $ref: '#/components/schemas/incoming-payment'
      additionalProperties: false
      examples:
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasPreviousPage: true
            last: 10
          result:
            - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              incomingAmount:
                value: '250'
                assetCode: USD
                assetScale: 2
              receivedAmount:
                value: '250'
                assetCode: USD
                assetScale: 2
              expiresAt: '2022-04-12T23:20:50.52Z'
              createdAt: '2022-03-12T23:20:50.52Z'
              updatedAt: '2022-04-01T10:24:36.11Z'
              description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
              externalRef: Coffee w/ Mo on 10 March 22
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasNextPage: true
            first: 10
          result:
            - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              incomingAmount:
                value: '250'
                assetCode: USD
                assetScale: 2
              receivedAmount:
                value: '250'
                assetCode: USD
                assetScale: 2
              expiresAt: '2022-04-12T23:20:50.52Z'
              createdAt: '2022-03-12T23:20:50.52Z'
              updatedAt: '2022-04-01T10:24:36.11Z'
              description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
              externalRef: Coffee w/ Mo on 10 March 22
    list-outgoing-payments:
      title: list-outgoing-payments
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        result:
          type: array
          items:
            $ref: '#/components/schemas/outgoing-payment'
      additionalProperties: false
      examples:
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasNextPage: true
            first: 10
          result:
            - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
              accountId: 'https://openpayments.guide/alice/'
              failed: false
              receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
              receiveAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              sendAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              sentAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              description: APlusVideo subscription
              externalRef: 'customer: 847458475'
            - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
              accountId: 'https://openpayments.guide/alice/'
              failed: false
              receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
              sendAmount:
                value: '7026'
                assetCode: USD
                assetScale: 2
              receiveAmount:
                value: '7026'
                assetCode: USD
                assetScale: 2
              sentAmount:
                value: '7026'
                assetCode: USD
                assetScale: 2
              createdAt: '2022-03-12T23:20:50.52Z'
              updatedAt: '2022-04-01T10:24:36.11Z'
              description: Thank you for your purchase at ShoeShop!
              externalRef: INV2022-8943756
    list-quotes:
      title: list-quotes
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        result:
          type: array
          items:
            $ref: '#/components/schemas/quote'
      additionalProperties: false
      examples:
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasNextPage: true
            first: 10
          result:
            - id: 'https://openpayments.guide/alice/quotes/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
              accountId: 'https://openpayments.guide/alice/'
              receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
              receiveAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              sendAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              createdAt: '2022-03-12T23:20:50.52Z'
              expiresAt: '2022-04-12T23:20:50.52Z'
            - id: 'https://openpayments.guide/alice/quotes/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
              accountId: 'https://openpayments.guide/alice/'
              receivingPayment: 'https://openpayments.guide/shoeshop/incoming-payments/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
              sendAmount:
                value: '2500'
                assetCode: USD
                assetScale: 2
              receiveAmount:
                value: '2198'
                assetCode: EUR
                assetScale: 2
              createdAt: '2022-04-01T10:24:36.11Z'
              expiresAt: '2022-05-01T10:24:36.11Z'
  securitySchemes:
    GNAP:
      name: Authorization
      type: apiKey
      in: header
      description: |-
        The API uses the Grant Negotiation and Authorization Protocol for authorization. An access token must be acquired from an authorization server before accessing the API and then provided in the request headers using the prefix `GNAP`.

        All requests must also be signed using a client key over some select headers and a digest of the request body.
  responses:
    '401':
      description: Authorization required
      headers:
        WWW-Authenticate:
          schema:
            type: string
          description: The address of the authorization server for grant requests in the format `GNAP as_uri=<URI>`
    '403':
      description: Forbidden
security:
  - GNAP: []
